services:
  - docker
  
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
  - ls -lah
  - docker build -t gabrielfeitosa/avaliacao -f Dockerfile.build .
  - docker run --name webe2e -d gabrielfeitosa/avaliacao
  - docker run -it --privileged --rm --link webe2e:webe2e -v $(pwd):/protractor --entrypoint=/bin/bash webnicer/protractor-headless -c "cd frontend && npm install && /protractor.sh e2e-test/conf.js"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push gabrielfeitosa/avaliacao

